In [2]:
import pandas as pd
import numpy as np
import chart_studio.plotly as py 
import plotly.graph_objs as go #importing graphical objects
#import seaborn as sns
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

from urllib.request import urlopen
import json
import plotly.express as px

from uszipcode import SearchEngine

import matplotlib.pyplot as plt
import seaborn as sns

c:\Users\QXZ29G0\Anaconda\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning:

Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning

In [3]:
#open s/s and save it in dataframe
FG_PB_df = pd.read_csv('RAW_NON_COLLAPSED_LEAD_CONV_112022_BMW1.CSV')

C:\Users\q555834\AppData\Local\Temp\ipykernel_12432\406807393.py:2: DtypeWarning:

Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.

In [4]:
FG_PB_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2897444 entries, 0 to 2897443
Data columns (total 31 columns):
 #   Column                    Dtype
---  ------                    -----
 0   #REPORT_DATE              int64
 1   LEAD_ID                   int64
 2   LEAD_FORWARDED_DATE       object
 3   LEAD_RECIEVED_DATE        object
 4   CENTER_ID                 int64
 5   LOCATION_CODE             int64
 6   LINEMAKE_ID               float64
 7   SOURCE_TYPE               object
 8   SOURCE_ORIGIN             object
 9   SOURCE_DESC               object
 10  SOURCE_LABEL              object
 11  TRACKING                  object
 12  CONV_DAYS                 float64
 13  VEHICLE_TYPE              object
 14  CONV_IND                  object
 15  DUPE_IND                  object
 16  RTL_PROCESS_DATE          object
 17  RTL_CENTER_ID             float64
 18  LEAD_GROUP_ID             float64
 19  RTL_GROUP_ID              float64
 20  VIN_NUMBER                object
 21  LEAD_CUSTOMER_FIRST_NAME  object
 22  LEAD_CUSTOMER_LAST_NAME   object
 23  LEAD_ADDRESS_LINE1        object
 24  LEAD_ADDRESS_LINE2        object
 25  LEAD_ADDRESS_CITY         object
 26  LEAD_ADDRESS_STATE        object
 27  LEAD_ADDRESS_ZIP          object
 28  LEAD_PHONE#               object
 29  LEAD_EMAIL_ADDRESS        object
 30  FS_CONV_IND               object
dtypes: float64(5), int64(4), object(22)
memory usage: 685.3+ MB

In [5]:
FG_PB_df.head()

,#REPORT_DATE,LEAD_ID,LEAD_FORWARDED_DATE,LEAD_RECIEVED_DATE,CENTER_ID,LOCATION_CODE,LINEMAKE_ID,SOURCE_TYPE,SOURCE_ORIGIN,SOURCE_DESC,...,LEAD_CUSTOMER_FIRST_NAME,LEAD_CUSTOMER_LAST_NAME,LEAD_ADDRESS_LINE1,LEAD_ADDRESS_LINE2,LEAD_ADDRESS_CITY,LEAD_ADDRESS_STATE,LEAD_ADDRESS_ZIP,LEAD_PHONE#,LEAD_EMAIL_ADDRESS,FS_CONV_IND
0,112022,30022190,04/06/2022 08:38:07,04/06/2022 08:38:07,31026,1,1.0,DEALER SOURCED,DEALER WEBSITE,Dealer Website - ePricer,...,EDDIE,GIRON,NaN,NaN,NaN,NaN,NaN,(617)9329637,EDDIEJGIRON@GMAIL.COM,N
1,112022,30022191,04/06/2022 08:36:39,04/06/2022 08:36:39,36640,1,1.0,DEALER SOURCED,DEALER WEBSITE,Dealer Website - Request More Info,...,MARISA,MITROS,1 Not Available,NaN,1 Not Available,NaN,61101,(215)8737855,MITROS3432@GMAIL.COM,N
2,112022,30022192,04/06/2022 08:37:46,04/06/2022 08:37:46,46891,2,1.0,DEALER SOURCED,DEALER WEBSITE,Dealer Website - ePricer,...,LISA,STEIN,NaN,NaN,NaN,NaN,NaN,No Number Given,LISASTEIN129@GMAIL.COM,N
3,112022,30022193,04/06/2022 08:37:29,04/06/2022 08:37:29,46891,1,1.0,DEALER SOURCED,DEALER WEBSITE,Dealer Website - Finance Offer,...,JAMES,EDGE,15667 67th Ct N,NaN,Loxahatchee,NaN,33470,(561)6763647,JIMEDGE@ICLOUD.COM,N
4,112022,30022194,04/06/2022 08:38:44,04/06/2022 08:38:44,50929,1,1.0,DEALER SOURCED,DEALER WEBSITE,Dealer Website - ePricer,...,CALVIN,CHECKINSON,NaN,NaN,NaN,NaN,NaN,(813)7344879,CHECKINSON@HOTMAIL.COM,N

In [7]:
print(FG_PB_df.columns)

Index(['#REPORT_DATE', 'LEAD_ID', 'LEAD_FORWARDED_DATE', 'LEAD_RECIEVED_DATE',
       'CENTER_ID', 'LOCATION_CODE', 'LINEMAKE_ID', 'SOURCE_TYPE',
       'SOURCE_ORIGIN', 'SOURCE_DESC', 'SOURCE_LABEL', 'TRACKING', 'CONV_DAYS',
       'VEHICLE_TYPE', 'CONV_IND', 'DUPE_IND', 'RTL_PROCESS_DATE',
       'RTL_CENTER_ID', 'LEAD_GROUP_ID', 'RTL_GROUP_ID', 'VIN_NUMBER',
       'LEAD_CUSTOMER_FIRST_NAME', 'LEAD_CUSTOMER_LAST_NAME',
       'LEAD_ADDRESS_LINE1', 'LEAD_ADDRESS_LINE2', 'LEAD_ADDRESS_CITY',
       'LEAD_ADDRESS_STATE', 'LEAD_ADDRESS_ZIP', 'LEAD_PHONE#',
       'LEAD_EMAIL_ADDRESS', 'FS_CONV_IND'],
      dtype='object')

In [6]:
FG_Centers = FG_PB_df.groupby('CENTER_ID', as_index=False)['CONV_THIS_CENTER'].count()

KeyError: 'Column not found: CONV_THIS_CENTER'

In [ ]:
FG_Centers

     CENTER_ID  CONV_THIS_CENTER
0         4497             10112
1         4514              9219
2         4618             13912
3         4637             13717
4         4660              8120
..         ...               ...
345      96628              9134
346      96644              2220
347      96717              5463
348      96733             11827
349      96774              1453

[350 rows x 2 columns]

In [ ]:
FG_df_42164 = FG_PB_df[FG_PB_df['CENTER_ID'] == 42164]

In [ ]:
FG_df_42164_Filtered = FG_PB_df[(FG_PB_df['CENTER_ID'] == 42164)&(FG_PB_df['CONV_THIS_CENTER'] == 1)&(FG_PB_df['TRACKED_FOR_KPI_PERFORMANCE'] == 'Y')]

In [ ]:
FG_df_42164_Filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1125 entries, 4650 to 2772444
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   REPORT_DATE                  1125 non-null   int64
 1   LEAD_ID                      1125 non-null   int64
 2   SEQUENCE_ID                  1125 non-null   int64
 3   BMWGROUP_ID                  1125 non-null   int64
 4   CENTER_ID                    1125 non-null   int64
 5   CUSTOMER_NAME                1125 non-null   object
 6   LOCATION_ID                  1125 non-null   int64
 7   LEAD_FORWARDED_DATE          1125 non-null   object
 8   CAMPAIGN                     1125 non-null   object
 9   LEAD_SOURCE                  1125 non-null   object
 10  TRACKED_FOR_KPI_PERFORMANCE  1125 non-null   object
 11  VEHICLE_TYPE                 1125 non-null   object
 12  RETAIL_VEHICLE_TYPE          1125 non-null   object
 13  LEAD_ADDRESS_LINE1           999 non-null    object
 14  LEAD_ADDRESS_LINE2           0 non-null      object
 15  LEAD_ADDRESS_CITY            999 non-null    object
 16  LEAD_ADDRESS_STATE           0 non-null      object
 17  LEAD_ADDRESS_ZIP             999 non-null    object
 18  LEAD_PHONE#                  1125 non-null   object
 19  LEAD_EMAIL_ADDRESS           1125 non-null   object
 20  CONVERSION_DAYS              1125 non-null   float64
 21  CONV_THIS_CENTER             1125 non-null   int64
 22  CONV_OTHER_CENTER            1125 non-null   int64
 23  VIN_NUMBER                   1125 non-null   object
 24  RETAIL_CUSTOMER_NAME         1125 non-null   object
 25  PROCESS_DATE                 1125 non-null   object
 26  FS_CONV                      1125 non-null   int64
dtypes: float64(1), int64(9), object(17)
memory usage: 246.1+ KB

In [ ]:
FG_df_42164_Filtered.to_csv('Data/CRM/NOV/FG_PB_42164.csv', index = True)

In [ ]:
FG_PB_NODUPS_df = FG_PB_df.drop_duplicates(subset='VIN_NUMBER', keep="first")
FG_PB_NODUPS_df

,REPORT_DATE,LEAD_ID,SEQUENCE_ID,BMWGROUP_ID,CENTER_ID,CUSTOMER_NAME,LOCATION_ID,LEAD_FORWARDED_DATE,CAMPAIGN,LEAD_SOURCE,...,LEAD_ADDRESS_ZIP,LEAD_PHONE#,LEAD_EMAIL_ADDRESS,CONVERSION_DAYS,CONV_THIS_CENTER,CONV_OTHER_CENTER,VIN_NUMBER,RETAIL_CUSTOMER_NAME,PROCESS_DATE,FS_CONV
0,102022,29175924,100000,42676997,26718,GALLER MICHAEL,1,01/13/2022 22:38:28,DEALER SOURCED,Darwin Online Digital Retailing,...,93117,No Number Given,0-WALKOUT.BUSHY@ICLOUD.COM,NaN,0,0,NaN,NaN,NaN,0
17,102022,29201221,100008,16158923,21234,ROSOFF CHRIS,1,01/15/2022 21:49:10,DEALER SOURCED,Dealer Website - ePricer,...,30752,(321)2006264,00-PILLAGE-MELANIN@ICLOUD.COM,12.0,1,0,5UXCR4C06N9L04148,BETH A ROSOFF,01/27/2022,0
30,102022,29628873,100014,19613024,42164,HERNANDEZ RICARDO,1,02/28/2022 14:14:44,FS,FS Lease Lead 270,...,78045,No Number Given,001RHC@GMAIL.COM,61.0,1,0,5UXTA6C05N9M19469,M RICARDO C HERNANDEZ,04/30/2022,1
39,102022,31027869,100018,31726321,26167,TULABANDULA HARIPAVANSAI,1,07/09/2022 18:45:46,INTERNET - BMW i,BMWUSA Test Drive Appointment,...,78717,No Number Given,00_CARS.ROOFERS@ICLOUD.COM,18.0,1,0,WBY73AW00NFN11486,MR HARI TULABANDULA,07/27/2022,1
66,102022,28517602,100028,42104629,26747,GARCIA JENNIFER,1,11/08/2021 13:49:24,DEALER SOURCED,Dealer Phone Lead,...,NaN,No Number Given,017JENJEN4SUE@GMAIL.COM,81.0,1,0,WBS2U7C01L7E99187,MR OSCAR GARCIA,01/28/2022,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2775733,102022,31942187,1188941,15033458,40713,KLEPPER JUSTIN,1,09/07/2022 21:23:21,DEALER SOURCED,Dealer Website - Digital Retailing - Accelerat...,...,19333,(973)4592879,JSTN5781@YAHOO.COM,6.0,1,0,3MW5R7J09M8C06350,MR JUSTIN T KLEPPER,09/13/2022,0
2775739,102022,31186503,954704,22094127,66788,HARRIS BYRON,3,07/20/2022 11:06:32,DEALER SOURCED,Dealer Website - Digital Retailing - Accelerat...,...,28269,(704)6997707,GRAPHIXSTUDIOB@GMAIL.COM,7.0,1,0,5UXCR6C01N9N31890,KAREN ELIZABETH HARRIS,07/27/2022,1
2775746,102022,31270936,1925604,34455311,10729,HERNANDEZ ENRIQUE,2,07/26/2022 12:42:55,INTERNET,BYO - Get A Quote,...,85018,No Number Given,ENRIQUEHERNANDEZ24@GMAIL.COM,49.0,1,0,WBABC4C58KBU96250,ENRIQUE HERNANDEZ GONZALEZ,09/13/2022,0
2775747,102022,29047573,1925604,42575384,10729,HERNANDEZ ENRIQUE,1,12/31/2021 14:40:16,INTERNET,BYO - Test Drive Request,...,85193,(559)7068453,EN_HERNANDEZ@YAHOO.COM,148.0,1,0,5YM23EC03N9M63138,MR ENRIQUE HERNANDEZ,05/28/2022,0
2775786,102022,29095391,550474,42617537,36021,HOLTCAMP RYAN,1,01/05/2022 17:43:50,DEALER SOURCED,Darwin Online Digital Retailing,...,98607,No Number Given,RHOLTCAMP@ADAIRFINANCIAL.COM,269.0,1,0,WBAKF9C5XCE859426,MR RYAN D HOLTCAMP,10/01/2022,0

In [ ]:
FG_df_42164_NODUPS_Filtered = FG_PB_NODUPS_df[(FG_PB_NODUPS_df['CENTER_ID'] == 42164)&(FG_PB_NODUPS_df['CONV_THIS_CENTER'] == 1)&(FG_PB_df['TRACKED_FOR_KPI_PERFORMANCE'] == 'Y')]

C:\Users\q555834\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [ ]:
FG_df_42164_NODUPS_Filtered.to_csv('Data/CRM/NOV/FG_PB_NODUPS_42164.csv', index = True)